name = "EmissionModels"
uuid = "1e2dd27c-41a5-43b2-863c-3eddd0c72c67"
version = "1.0.0-DEV"
authors = ["Ryan Senne"]

[deps]
DensityInterface = "b429d917-457f-4dbc-8f4c-0cc954292b1d"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"

[compat]
DensityInterface = "0.4.0"
StatsAPI = "1.8.0"
julia = "1.6.7"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
