name = "EmissionModels"
uuid = "1e2dd27c-41a5-43b2-863c-3eddd0c72c67"
version = "1.0.0-DEV"
authors = ["Ryan Senne"]

[deps]
DensityInterface = "b429d917-457f-4dbc-8f4c-0cc954292b1d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"

[compat]
DensityInterface = "0.4.0"
Random = "1.11.0"
SpecialFunctions = "2.6.1"
StatsAPI = "1.8.0"
julia = "1.6.7"
