name = "EmissionModels"
uuid = "1e2dd27c-41a5-43b2-863c-3eddd0c72c67"
version = "1.0.0-DEV"
authors = ["Ryan Senne"]

[deps]
DensityInterface = "b429d917-457f-4dbc-8f4c-0cc954292b1d"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"

[compat]
DensityInterface = "0.4.0"
Distributions = "0.25.122"
LinearAlgebra = "1.12.0"
LogExpFunctions = "0.3.29"
Optim = "1.13.3, 2"
Random = "1.11.0"
SpecialFunctions = "2.6.1"
StatsAPI = "1.8.0"
julia = "1.9"
